spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EventSphere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Kajal@@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # for dev/assessment. Use 'validate' or migrations in prod
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: VerySecretKeyForAssessmentChangeThis
    expirationMs: 3600000

logging:
  level:
    root: INFO
    org.example: DEBUG

# springdoc (swagger) options (defaults work, this just sets path)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
